### ISSUE TITLE
Phase-0 Unit-1 Week-1 blog reviews

### ISSUE THREAD

**Issue by annewchen** [gaelbergeron/gaelbergeron.github.io#2]
Great organization of ideas in your git blog. The concepts really flowed together. Also enjoyed those bits of data pieces included at the end. 
It was inspiring reading your chef-in-the-kitchen blog. A camaraderie through the common fears you mentioned and everyone's dedication to learning coding is what will make this program fly by :)

**Comment by gaelbergeron** [comment]
Thank you so much Anne for the great feedback! I really appreciate.
